#!/bin/bash

if [[ -z ${DESKPRO_KEY} ]]; then
  echo Please set the environment variable DESKPRO_KEY
  exit 1
fi

sm2 -start MONGO 

sm2 -start THIRD_PARTY_DEVELOPER_FRONTEND THIRD_PARTY_APPLICATION THIRD_PARTY_DEVELOPER THIRD_PARTY_DELEGATED_AUTHORITY API_PLATFORM_MICROSERVICE THIRD_PARTY_ORCHESTRATOR API_PLATFORM_EVENTS

sm2 -start EMAIL HMRC_EMAIL_RENDERER DIGITAL_CONTACT_STUB API_PLATFORM_ORGANISATION INTERNAL_AUTH UPSCAN_STUB

sm2 -start API_PLATFORM_DESKPRO --appendArgs '{"API_PLATFORM_DESKPRO":["-Ddeskpro.api-key='${DESKPRO_KEY}'"]}'

./run_local.sh
