#!/bin/bash

sm2 -start MONGO 

sm2 -start THIRD_PARTY_DEVELOPER_FRONTEND THIRD_PARTY_APPLICATION THIRD_PARTY_DEVELOPER THIRD_PARTY_DELEGATED_AUTHORITY API_PLATFORM_MICROSERVICE THIRD_PARTY_ORCHESTRATOR

sm2 -start API_PLATFORM_ORGANISATION

./run_local.sh
